{% set version = "0.13.1" %}

package:
  name: flask-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Flask-Cache/Flask-Cache-{{ version }}.tar.gz
  sha256: 90126ca9bc063854ef8ee276e95d38b2b4ec8e45fd77d5751d37971ee27c7ef4

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
    - flask
  run:
    - python
    - flask

test:
  imports:
    - flask_cache

about:
  home: http://github.com/thadeusb/flask-cache
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Adds cache support to your Flask application'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
