travis:
  secure:
    BINSTAR_TOKEN: LmYTDbDi6xc0tfJ844kkKaF4xNvmzghG4N0z2e/tW1LDuDRvnuPFJTUjwI91ph/j2hHkedhHhWl5mBT7TdP0xqqpRobvDHxZ3MjVqM0wx+W3MM+N2vtGu89D11NnF046xRJ85DtwYx0gURZd2mcl8ug6YcSstaFIg5yE4Y5klgVKN9ReZ37ryH/DozoTqQSSQfZDxB1Cjq59shE75ADJChBOhDFpxMznHIli0PNh+lfy1fXfKuXb4J12xauEH2GeSVYpEureozNPkWWGAyF5m+f7qaaBeyP1rZZZUVZ4Bo9607B+pgSqZGuNfTn8+MBTY7LojsqvjtvSssNC8x2QlMbg6glmRnWvvLeeOAYmxJ8jvduNp0X8nt6fWCy6H28k6o0QBAUAmL27qwSHX3b2OMRPE1L9dr8ygL3cAuyG/Ul+CCJzLcHKVh3ZsWEcoomWKKa0ljqDXRq24y8qHXEJefpScbPUxu6/pC/TlDcZVAxiH7cvK6UFUegMYEIerK4a6R+e3nuA+st5DZzrKKuvHNB2Fg/dly2Z8/aLD9k0Hr29regXICr6lyuLnDlHHkOCSSoBfzRrLvghtszoV66+jSl0SqNhYNOlCFhxxw4dWD3KMkKaOKxSaHy+V0ZbkUET1C/sFobKGIfo4qnaTDR+qpPJpZNNAX1D1SB5kR58urI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
