travis:
  secure:
    BINSTAR_TOKEN: iLujUmz7mxr7IiCCAhwkmDrL7I5PiX+Vd2Xaqn6lUm2ClReUfVuw4OkD51wEytVYGXc33Gz4QmXdTrMjh/OxLjqoKfOY4tzYDYwxBMPVv8r+N8A51CfVrWu4qwElguZ/prYPO9iZ+lNO+fX0mQsmeJuSp/GsBMEWw6gokbDCQtMlpQqtskPWyxefufClZY0HI2iLNRVvC9sjx+6RlDpiRJlqq53XmhPZfASLIcwC7QumsyD0JQKra4JctDTp7sdNL9auWp/eqokG3UE/4dFeMwkvQ86CF7SVbB1eOOxW2iBHjuAJha+ZK4y+soyVuqD2hHIGXkbYQCKw8KdDk0639ashWoJNPsn8XVTQnFsiDcYZfIJzVbafrSr5AWVeWBGUwH0hAsBaP4FkGCVNiX9uw9/urDINWLnTOcHtHiXLqftAUs2NvEm+EnlVls7Y/6Gk43OXnADru/MvuR3LRVmuIQeDbTPB/4ce/X2FLUTC0lxtjSSQooqQqxfp5srlcLlPZfAJPX+UcwgeHrgL7cVMkbTmMwiIMAXCTL47VbYwJPJMp7nQQYBJGzicX4S+T2Gv0kFF/zgutbWdd3cYkVPGvt1mJB0BABbWtpX2k1xv0mqeE5nso5+7wAsOBdE/nuqy0eFvQ4P5UR0pUQ37ELT7A1ZS8kgDI4ABITEEKIMZmkE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
