travis:
  secure:
    BINSTAR_TOKEN: Ohh7fdijsKepsf6Tmbrs0AjWPJfn+2IethaClFDt1fF0IPykMlZFyn76wfSsYMBr0au3dnFalGDph9+l9JvA1Md5ik3L8aRZQN/q5fNfEfpXUa1gXTdY0btV4DYySRkujdlbRpcjzahYXgdm1xazYnqseUbYUcF42JhPpWTBJ771mtBMhU8VSW2mvAodp+ZBn8fvNXS4pSzUw0pvEAQB0OwMqGRdXWtujqKjzu2DBZphvAQNE1g1rwEeTt5yIQ+J+oAwpQ4neQ+fOVXkdOaRX/ucqTFS0iOgena5CQCijzNB8LKzMrqjeC16t1mEWBwl6ETh8NN0u88pyKGteyV7q4ksmWazRWtnYmbz2XMe4KxzEGrtkn7UVpd7BuhoXclsZY+53V5exsYLR+qK9jNZIrhIOTvOhwHcdtoZnBwXD9zaRPbvXH+Vcx3mxoxrux7lbyC8MgpNhVsOWCc32lKufrc1MtNSRfOoloQNyxEw1PCqRWBDLkeCrMSEMbWJOnAmZsft43URjaB4SeraoQxv8tWqtzsODAf5kqdUKZFmn9qKbYcyVb4DX0s8H5hKEEvKmLu7MS2y9ggePK0s0vgIonZ4ql+7CNdH1X5hZz8VeAjgwDUBh8sX2KMm3RXJddMS/bxHRPi2M2xncG2hZn0GYIhBRaY6ZTu2BM222Yaudls=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
